### PR TITLE
Enhancement that disables BLJing similar as on DS

### PR DESCRIPTION
**Pull request by niansa**
A little hacky but might be the shortest way

### CODE REVIEW

**Comment by gek169** [comment]
I thought the goal of this project was to make it as accurate and well-documented as possible?

**Comment by nadiaholmquist** [comment]
There is already a ifdef for the shindou edition that fixes BLJs, though to make it more accessible it should probably be a bugfix option in config.h like many other such changes are.

**Comment by ipluxteamx** [comment]
OK

**Comment by Jan200101** [comment]
this is the sm64 n64 decomp repo, being an exact decomp is the goal, this does not belong here

**Comment by niansa** [comment]
will leave it as a pull request for people who are interested in it

**Pull request closed without merging**
