### PR TITLE
Adding build guide for Windows 10

### PR DESCRIPTION
**Pull request by bonjorno7**
Also fixing some formatting inconsistencies

### CODE REVIEW

**Comment by bonjorno7** [comment]
Good idea, I'll do it first thing tomorrow.

**Comment by bonjorno7** [comment]
This oughta do it

**Comment by bonjorno7** [comment]
Yeah that'd be awesome! You should be able to copy most of the win10 guide.

**Comment by mountainflaw** [comment]
I asked about this with the other developers, and they seem to disagree on including this as it contains a guide for setting up WSL, which is out of scope. I'm alright if you post it in the public Discord guild, however.

**Pull request closed without merging**
