### PR TITLE
Use array subscripts instead of pointer math where applicable

### PR DESCRIPTION
**Pull request by ZLima12**
I noticed that in several places, pointer math was being used instead of array subscripts. This should fix most of those instances. I made sure that the output from compilation was not changed.

### CODE REVIEW

**Comment by nim-ka** [comment]
Sorry, but these pointer expressions are there because they're required to match the EU/PAL version of the game. Your PR doesn't match that version

**Comment by ZLima12** [comment]
Hmm, I see. Do you mean that the compilation output is different? Or is there some kind of debug information in that version that specifies that that's how the source code was written?

**Comment by ZLima12** [comment]
Additionally, perhaps a subset of these changes would still match the PAL version?

**Comment by nim-ka** [comment]
Yeah, the compiler's output is different, because it can generate different assembly with pointer math vs. with array indexing.
I'd be surprised if any of these changes match PAL, because they were probably initially written as array indexes before the PAL version was decompiled, and changed to pointer expressions just to match PAL.

**Comment by ZLima12** [comment]
Huh, I thought that array indexing was supposed to be equivalent to pointer math. It's odd that in places near these changes, array subscripts are used without a problem. I wonder why it would work there, but not in these places.

**Comment by nim-ka** [comment]
It's definitely *equivalent*, but equivalent code can generate vastly different assembly, especially when compiled with optimizations. The programmers probably just wrote it like that; their style was abhorrent, it wouldn't surprise anyone

**Comment by ZLima12** [comment]
Alright, perhaps I overestimated the consistency of the programmers. Thanks for the info, I'll close this.

**Comment by JoshDuMan** [comment]
Yes, I can tell you that specifically that wiggler code was tricky to match and the first one we realized needed to be that way to match for the PAL release. The compiler is frustrating sometimes. The effort is appreciated though :) If you wish to help out in other ways, picking a file with unlabeled things can go a long way. Many of the behavior files in /src/behaviors/ or whatever its called are good files to start with.

**Comment by AloXado320** [comment]
Just to note, only a small part of this PR is merged into the main repo since it still matched all version decompiled.
`find_poison_gas_level` and `bhv_mips_find_furthest_waypoint_to_mario`

**Pull request closed without merging**
