### PR TITLE
Mario keeps randomly crouching

### PR DESCRIPTION
**Pull request by BlueStaggo**
For some reason, I cannot make an issue. When I'm playing the PC port, Mario just randomly crouches sometimes when I'm not pressing the crouch key. My crouch key is Left Shift. I am running Super Mario 64 on Windows 10 x64 1909 using GCC 10.2.0.

### CODE REVIEW

**Comment by GlowingUmbreon** [comment]
This is the decop repo, not the port repo. Make a issue on the PC port's github.

**Comment by BlueStaggo** [comment]
Ok Thanks for letting me know.

**Comment by BlueStaggo** [comment]
Actually, I can't even submit an issue to the decomp repo or the pc port repo. What do I do now?

**Comment by GlowingUmbreon** [comment]
> Actually, I can't even submit an issue to the decomp repo or the pc port repo. What do I do now?

I guess you could try to fix it yourself on the port's repo and then create the pull request?

**Comment by ProjectRevoTPP** [comment]
Do not reopen this. This PR does not belong here.

**Comment by gek169** [comment]
mario's got a mental health condition, maybe?

**Pull request closed without merging**
