### PR TITLE
NDS Expansion Pack Support

### PR DESCRIPTION
**Pull request by quimodotcom**
NDS Expansion Pack Support

### CODE REVIEW

**Comment by networkfusion** [comment]
Wrong repo!!!

**Comment by quimodotcom** [comment]
> Wrong repo!!!

I dont think this is the wrong repo. This is the DSI SM64 Repo isnt it???

**Comment by Jan200101** [comment]
You have opened a Pull Request on the SM64 N64 decompile repo
No ports here

**Comment by quimodotcom** [comment]
> You have opened a Pull Request on the SM64 N64 decompile repo
> No ports here

Whoops... sorry! Must of had this repo in my favourites...

**Pull request closed without merging**
